### ISSUE TITLE
Many pathways are not renderable

### ISSUE THREAD

**Issue by pennatula** [wikipathways/reactome2gpml-converter#29]
This is the error I get using the converter.
GKBReader.createRenderableFromType(): java.lang.ClassNotFoundException: org.gk.render.RenderableEntitySet
java.lang.ClassNotFoundException: org.gk.render.RenderableEntitySet
	at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at org.gk.persistence.GKBReader.createRenderableFromType(GKBReader.java:648)
	at org.gk.persistence.GKBReader.createRenderableFromElement(GKBReader.java:632)
	at org.gk.persistence.GKBReader.openNodes(GKBReader.java:474)
	at org.gk.persistence.GKBReader.openProcess(GKBReader.java:398)
	at org.gk.persistence.GKBReader.openProcess(GKBReader.java:312)
	at org.gk.persistence.DiagramGKBReader.openProcess(DiagramGKBReader.java:68)
	at org.gk.persistence.DiagramGKBReader.openDiagram(DiagramGKBReader.java:62)
	at org.reactome.convert.common.AbstractConverterFromReactome.queryPathwayDiagram(AbstractConverterFromReactome.java:199)
	at org.gk.gpml.ReactometoGPML2013.convertPathway(ReactometoGPML2013.java:489)
	at org.gk.gpml.CLIConverter.convertReactomeToGPML(CLIConverter.java:126)
	at org.gk.gpml.CLIConverter.convertReactomeToGPMLByID(CLIConverter.java:162)
	at org.gk.gpml.CLIConverter.main(CLIConverter.java:42)

The renderable entity set (equivalent to the Pathway Class on our end) seems to be missing. 

List of non renderable pathways in version 50 : https://cloud.bigcat.maastrichtuniversity.nl/public.php?service=files&t=e5900286773689ce08820c088bd57f5e

**Comment by pennatula** [comment]
Fixed with updated reactome.jar
