### ISSUE TITLE
Overview of pathways doesn't link them

### ISSUE THREAD

**Issue by egonw** [wikipathways/reactome2gpml-converter#31]
For example, if I compare http://www.wikipathways.org/index.php/Pathway:WP1849 with the original [0] then the arrows seem to be missing.

0.http://www.reactome.org/PathwayBrowser/#DB=gk_current&FOCUS_SPECIES_ID=48887&FOCUS_PATHWAY_ID=556833

**Comment by pennatula** [comment]
converting pathway #556833 Metabolism of lipids and lipoproteins...
Creating new GPML pathway 556835
Warning creating a new DataSource with systemCode Re and null fullName!
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.pathvisio.core.biopax.BiopaxNode.<init>(BiopaxNode.java:41)
	at org.pathvisio.core.biopax.PublicationXref.<init>(PublicationXref.java:32)
	at org.gk.gpml.ReactometoGPML2013.addLitRef(ReactometoGPML2013.java:226)
	at org.gk.gpml.ReactometoGPML2013.convertNode(ReactometoGPML2013.java:520)
	at org.gk.gpml.ReactometoGPML2013.convertPathway(ReactometoGPML2013.java:794)
	at org.gk.gpml.CLIConverter.convertReactomeToGPML(CLIConverter.java:170)
	at org.gk.gpml.CLIConverter.convertReactomeToGPMLByID(CLIConverter.java:206)
	at org.gk.gpml.CLIConverter.main(CLIConverter.java:63)
Caused by: java.lang.IllegalArgumentException: Full name does not match for DataSource Re was null so it can not be changed to Reactome
	at org.bridgedb.DataSource.findOrRegister(DataSource.java:629)
	at org.bridgedb.DataSource.register(DataSource.java:595)
	at org.bridgedb.bio.DataSourceTxt.loadLine(DataSourceTxt.java:69)
	at org.bridgedb.bio.DataSourceTxt.loadAnInputStream(DataSourceTxt.java:63)
	at org.bridgedb.bio.DataSourceTxt.init(DataSourceTxt.java:42)
	at org.pathvisio.core.model.GpmlFormat.<clinit>(GpmlFormat.java:55)
	... 8 more

**Comment by egonw** [comment]
Anwesha, can you please try the following:

1. Replace

    DataSource ds = DataSource.getBySystemCode("Re");

with

    DataSource ds = DataSource.getExistingBySystemCode("Re");

2. initialize the DataSourceTxt yourself, at the very start of the convertPathway() method, with:

    DataSourceTxt.init();
